### ISSUE TITLE
Some links go to thaum.xyz

### ISSUE THREAD

**Issue by james-callahan** [prometheus-operator/runbooks#1]
e.g. on https://runbooks.prometheus-operator.dev/ the `TargetDown` link goes to https://runbooks.thaum.xyz/runbooks/general/targetdown/

I assume this line needs fixing: https://github.com/prometheus-operator/runbooks/blob/8f0e3967021ba82ed4b2f50f86dc7ff09d924bc9/config.yaml#L1

**Comment by paulfantom** [comment]
Sorry for the late reply. You are correct, could you create a PR?
