### ISSUE TITLE
What is the plan with runbooks ?

### ISSUE THREAD

**Issue by NargiT** [prometheus-operator/runbooks#6]
Today we have only 10% documented, is there a plan to document 90% that left ? Or we expect the community to contribute ? 
In our case we would like to help the L1 to be able to find quickly some documentation.

# List of all alert from **release-0.8**
Source of alerts https://github.com/prometheus-operator/kube-prometheus 

## 200 Status (10 alerts)
- alertmanagermembersinconsistent https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagermembersinconsistent 200
- targetdown https://runbooks.prometheus-operator.dev/runbooks/general/targetdown 200
- kubeapierrorbudgetburn https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeapierrorbudgetburn 200
- kubelettoomanypods https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubelettoomanypods 200
- kubepersistentvolumefillingup https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubepersistentvolumefillingup 200
- kubeschedulerdown https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeschedulerdown 200
- prometheusbadconfig https://runbooks.prometheus-operator.dev/runbooks/prometheus/prometheusbadconfig 200
- prometheusduplicatetimestamps https://runbooks.prometheus-operator.dev/runbooks/prometheus/prometheusduplicatetimestamps 200
- prometheusoutofordertimestamps https://runbooks.prometheus-operator.dev/runbooks/prometheus/prometheusoutofordertimestamps 200
- prometheusrulefailures https://runbooks.prometheus-operator.dev/runbooks/prometheus/prometheusrulefailures 200

## 404 Status (90 alerts)
- alertmanagerclustercrashlooping https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerclustercrashlooping 404
- alertmanagerclusterdown https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerclusterdown 404
- alertmanagerclusterfailedtosendalerts https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerclusterfailedtosendalerts 404
- alertmanagerconfiginconsistent https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerconfiginconsistent 404
- alertmanagerfailedreload https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload 404
- alertmanagerfailedtosendalerts https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedtosendalerts 404
- nodenetworkinterfaceflapping https://runbooks.prometheus-operator.dev/runbooks/general/nodenetworkinterfaceflapping 404
- watchdog https://runbooks.prometheus-operator.dev/runbooks/general/watchdog 404
- aggregatedapidown https://runbooks.prometheus-operator.dev/runbooks/kubernetes/aggregatedapidown 404
- aggregatedapierrors https://runbooks.prometheus-operator.dev/runbooks/kubernetes/aggregatedapierrors 404
- cputhrottlinghigh https://runbooks.prometheus-operator.dev/runbooks/kubernetes/cputhrottlinghigh 404
- kubeapidown https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeapidown 404
- kubeapiterminatedrequests https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeapiterminatedrequests 404
- kubeclientcertificateexpiration https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeclientcertificateexpiration 404
- kubeclienterrors https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeclienterrors 404
- kubecontainerwaiting https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubecontainerwaiting 404
- kubecontrollermanagerdown https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubecontrollermanagerdown 404
- kubecpuovercommit https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubecpuovercommit 404
- kubecpuquotaovercommit https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubecpuquotaovercommit 404
- kubedaemonsetmisscheduled https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubedaemonsetmisscheduled 404
- kubedaemonsetnotscheduled https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubedaemonsetnotscheduled 404
- kubedaemonsetrolloutstuck https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubedaemonsetrolloutstuck 404
- kubedeploymentgenerationmismatch https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubedeploymentgenerationmismatch 404
- kubedeploymentreplicasmismatch https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubedeploymentreplicasmismatch 404
- kubehpamaxedout https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubehpamaxedout 404
- kubehpareplicasmismatch https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubehpareplicasmismatch 404
- kubejobcompletion https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubejobcompletion 404
- kubejobfailed https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubejobfailed 404
- kubeletclientcertificateexpiration https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeletclientcertificateexpiration 404
- kubeletclientcertificaterenewalerrors https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeletclientcertificaterenewalerrors 404
- kubeletdown https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeletdown 404
- kubeletplegdurationhigh https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeletplegdurationhigh 404
- kubeletpodstartuplatencyhigh https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeletpodstartuplatencyhigh 404
- kubeletservercertificateexpiration https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeletservercertificateexpiration 404
- kubeletservercertificaterenewalerrors https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeletservercertificaterenewalerrors 404
- kubememoryovercommit https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubememoryovercommit 404
- kubememoryquotaovercommit https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubememoryquotaovercommit 404
- kubenodenotready https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubenodenotready 404
- kubenodereadinessflapping https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubenodereadinessflapping 404
- kubenodeunreachable https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubenodeunreachable 404
- kubepersistentvolumeerrors https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubepersistentvolumeerrors 404
- kubepodcrashlooping https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubepodcrashlooping 404
- kubepodnotready https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubepodnotready 404
- kubeproxydown https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeproxydown 404
- kubequotaalmostfull https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubequotaalmostfull 404
- kubequotaexceeded https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubequotaexceeded 404
- kubequotafullyused https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubequotafullyused 404
- kubestatefulsetgenerationmismatch https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubestatefulsetgenerationmismatch 404
- kubestatefulsetreplicasmismatch https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubestatefulsetreplicasmismatch 404
- kubestatefulsetupdatenotrolledout https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubestatefulsetupdatenotrolledout 404
- kubeversionmismatch https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeversionmismatch 404
- kubestatemetricslisterrors https://runbooks.prometheus-operator.dev/runbooks/kube-state-metrics/kubestatemetricslisterrors 404
- kubestatemetricsshardingmismatch https://runbooks.prometheus-operator.dev/runbooks/kube-state-metrics/kubestatemetricsshardingmismatch 404
- kubestatemetricsshardsmissing https://runbooks.prometheus-operator.dev/runbooks/kube-state-metrics/kubestatemetricsshardsmissing 404
- kubestatemetricswatcherrors https://runbooks.prometheus-operator.dev/runbooks/kube-state-metrics/kubestatemetricswatcherrors 404
- nodeclocknotsynchronising https://runbooks.prometheus-operator.dev/runbooks/node/nodeclocknotsynchronising 404
- nodeclockskewdetected https://runbooks.prometheus-operator.dev/runbooks/node/nodeclockskewdetected 404
- nodefiledescriptorlimit https://runbooks.prometheus-operator.dev/runbooks/node/nodefiledescriptorlimit 404
- nodefilesystemalmostoutoffiles https://runbooks.prometheus-operator.dev/runbooks/node/nodefilesystemalmostoutoffiles 404
- nodefilesystemalmostoutofspace https://runbooks.prometheus-operator.dev/runbooks/node/nodefilesystemalmostoutofspace 404
- nodefilesystemfilesfillingup https://runbooks.prometheus-operator.dev/runbooks/node/nodefilesystemfilesfillingup 404
- nodefilesystemspacefillingup https://runbooks.prometheus-operator.dev/runbooks/node/nodefilesystemspacefillingup 404
- nodehighnumberconntrackentriesused https://runbooks.prometheus-operator.dev/runbooks/node/nodehighnumberconntrackentriesused 404
- nodenetworkreceiveerrs https://runbooks.prometheus-operator.dev/runbooks/node/nodenetworkreceiveerrs 404
- nodenetworktransmiterrs https://runbooks.prometheus-operator.dev/runbooks/node/nodenetworktransmiterrs 404
- noderaiddegraded https://runbooks.prometheus-operator.dev/runbooks/node/noderaiddegraded 404
- noderaiddiskfailure https://runbooks.prometheus-operator.dev/runbooks/node/noderaiddiskfailure 404
- nodetextfilecollectorscrapeerror https://runbooks.prometheus-operator.dev/runbooks/node/nodetextfilecollectorscrapeerror 404
- configreloadersidecarerrors https://runbooks.prometheus-operator.dev/runbooks/prometheus-operator/configreloadersidecarerrors 404
- prometheusoperatorlisterrors https://runbooks.prometheus-operator.dev/runbooks/prometheus-operator/prometheusoperatorlisterrors 404
- prometheusoperatornodelookuperrors https://runbooks.prometheus-operator.dev/runbooks/prometheus-operator/prometheusoperatornodelookuperrors 404
- prometheusoperatornotready https://runbooks.prometheus-operator.dev/runbooks/prometheus-operator/prometheusoperatornotready 404
- prometheusoperatorreconcileerrors https://runbooks.prometheus-operator.dev/runbooks/prometheus-operator/prometheusoperatorreconcileerrors 404
- prometheusoperatorrejectedresources https://runbooks.prometheus-operator.dev/runbooks/prometheus-operator/prometheusoperatorrejectedresources 404
- prometheusoperatorsyncfailed https://runbooks.prometheus-operator.dev/runbooks/prometheus-operator/prometheusoperatorsyncfailed 404
- prometheusoperatorwatcherrors https://runbooks.prometheus-operator.dev/runbooks/prometheus-operator/prometheusoperatorwatcherrors 404
- prometheuserrorsendingalertstoanyalertmanager https://runbooks.prometheus-operator.dev/runbooks/prometheus/prometheuserrorsendingalertstoanyalertmanager 404
- prometheuserrorsendingalertstosomealertmanagers https://runbooks.prometheus-operator.dev/runbooks/prometheus/prometheuserrorsendingalertstosomealertmanagers 404
- prometheuslabellimithit https://runbooks.prometheus-operator.dev/runbooks/prometheus/prometheuslabellimithit 404
- prometheusmissingruleevaluations https://runbooks.prometheus-operator.dev/runbooks/prometheus/prometheusmissingruleevaluations 404
- prometheusnotconnectedtoalertmanagers https://runbooks.prometheus-operator.dev/runbooks/prometheus/prometheusnotconnectedtoalertmanagers 404
- prometheusnotificationqueuerunningfull https://runbooks.prometheus-operator.dev/runbooks/prometheus/prometheusnotificationqueuerunningfull 404
- prometheusnotingestingsamples https://runbooks.prometheus-operator.dev/runbooks/prometheus/prometheusnotingestingsamples 404
- prometheusremotestoragefailures https://runbooks.prometheus-operator.dev/runbooks/prometheus/prometheusremotestoragefailures 404
- prometheusremotewritebehind https://runbooks.prometheus-operator.dev/runbooks/prometheus/prometheusremotewritebehind 404
- prometheusremotewritedesiredshards https://runbooks.prometheus-operator.dev/runbooks/prometheus/prometheusremotewritedesiredshards 404
- prometheustargetlimithit https://runbooks.prometheus-operator.dev/runbooks/prometheus/prometheustargetlimithit 404
- prometheustargetsyncfailure https://runbooks.prometheus-operator.dev/runbooks/prometheus/prometheustargetsyncfailure 404
- prometheustsdbcompactionsfailing https://runbooks.prometheus-operator.dev/runbooks/prometheus/prometheustsdbcompactionsfailing 404
- prometheustsdbreloadsfailing https://runbooks.prometheus-operator.dev/runbooks/prometheus/prometheustsdbreloadsfailing 404

**Comment by paulfantom** [comment]
We are adding them as we go and expect community to chime in with additional runbooks (that's why 404 page looks the way it looks).
