### ISSUE TITLE
Missing docs for kubernetes/kubehpamaxedout

### ISSUE THREAD

**Issue by webframp** [prometheus-operator/runbooks#8]
It looks like the alert for KubeHpaMaxedOut defined here: 
* https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/kubernetesControlPlane-prometheusRule.yaml#L250

Links to the following non-existent page:
* https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubehpamaxedout

Is the content somewhere else, could I help with a PR to migrate this page from somewhere else?

**Comment by paulfantom** [comment]
There is no page with a runbook for this alert and we are open to community contributions for such a page.
